JETAUTH/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("apps.urls")),
    path('auth/', include("profiles.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

apps/urls.py
from django.urls import path
from .views import Index

app_name = "apps"
urlpatterns = [
    path('', Index.as_view(), name="index")
]

profiles/urls.py
from django.urls import path
from .views import CreateUser, Login

app_name = "profiles"
urlpatterns = [
    path('register', CreateUser, name="register"),
    path('login', Login, name="login")
]

apps/models.py
from django.db import models
from django.conf import settings


# Create your models here.

class App(models.Model):
    created_by = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    app_name = models.CharField(max_length=100, unique=True)
    redirect_to_url = models.URLField()
    app_icon = models.ImageField(upload_to="icons", blank=True, null=True)
    app_category = models.CharField(max_length=80)
    app_access_data = models.CharField(max_length=300)
    app_public_key = models.CharField(max_length=300, unique=True)
    app_secret_key = models.CharField(max_length=100, unique=True)
    app_secret_key_hash = models.CharField(max_length=300)
    created_on = models.DateTimeField(auto_now=True)
    updated_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.app_name


class AllowedApps(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    app = models.ForeignKey(App, on_delete=models.CASCADE)
    last_login = models.DateTimeField(blank=True, null=True)
    allowed_on = models.DateTimeField(auto_now=True)
    number_of_logins = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.user.get_full_name + "-" + self.app.app_name

profiles/models.py
from django.contrib.auth.models import AbstractUser, UserManager
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.db import models
from django.utils.translation import gettext_lazy as _

# Create your models here.
from phonenumber_field.modelfields import PhoneNumberField


class MyUserManager(UserManager):
    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        username = email
        return self._create_user(username, email, password, **extra_fields)


class User(AbstractUser):
    genders = (
        ('female', 'Female'),
        ('male', 'Male'),
        ('secret', 'Rather not say'),
        ('other', 'Other, mention'),
    )
    nouns = (
        ('he', 'He/Him/His'),
        ('she', 'She/Her/Hers'),
        ('both', 'Both'),
        ('custom', 'Custom'),
    )

    username_validator = UnicodeUsernameValidator()

    username = models.CharField(
        _('username'),
        max_length=150,
        blank=True,
        null=True,
        unique=True,
        help_text=_('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )
    profile_picture = models.ImageField()
    email = models.EmailField(_('email address'), unique=True)
    middle_name = models.CharField(max_length=40, blank=True, null=True)
    other_name = models.CharField(max_length=40, blank=True, null=True)
    gender = models.CharField(max_length=12, choices=genders, null=True, blank=True)
    other_gender = models.CharField(_('Other gender'), null=True, max_length=100, blank=True)
    phone = PhoneNumberField(_('phone number'), unique=True, null=True, blank=True)
    pronoun = models.CharField(max_length=12, null=True, choices=nouns, blank=True)
    custom_pronoun = models.CharField(_('custom pronoun'), max_length=100, null=True, blank=True)
    country = models.CharField(max_length=30, blank=True, null=True)
    region = models.CharField(max_length=30, blank=True, null=True)
    address = models.CharField(max_length=60, blank=True, null=True)
    language = models.CharField(max_length=60, blank=True, null=True)
    occupation = models.CharField(max_length=60, blank=True, null=True)
    status = models.CharField(_('marital status'), max_length=34, blank=True, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = MyUserManager()

    @property
    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s %s %s' % (self.first_name, self.middle_name, self.last_name, self.other_name)
        return full_name.strip()

    @property
    def get_clean_name(self):
        """
        :return: first_name and last_name, with a space in between
        """
        clean_name = '%s %s' % (self.first_name, self.first_name)
        return clean_name.strip()

    @property
    def get_gender(self):
        if self.gender == "other":
            return self.other_gender.strip()
        return self.gender

    @property
    def get_user_noun(self):
        if self.pronoun == "custom":
            return self.custom_pronoun.strip()
        elif self.pronoun == "both":
            return "both he and she"
        return self.pronoun

apps/forms.py
from django import forms
from .models import App, AllowedApps


class AppForm(forms.ModelForm):
    class Meta:
        model = App
        fields = "__all__"

apps/views.py
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin


class Index(LoginRequiredMixin, TemplateView):
    template_name = "apps/index.html"

profiles/views.py
from django.conf import settings
from django.contrib import messages, auth
from django.shortcuts import render, redirect


# Create your views here.


def CreateUser(request):
    if request.user.is_authenticated:
        return redirect('apps:index')

    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get('password')
        username = request.POST.get('username') if request.POST.get('username') else email
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')

        User = settings.AUTH_USER_MODEL

        #         check if username is taken
        if User.objects.filter(username=username).exists():
            messages.error(request, message="Username is already taken")
            return redirect(request.path_info)
        elif User.objects.filter(email=email).exists():
            messages.error(request, message="Email is already taken")
            return redirect(request.path_info)
        else:
            user = User.objects.create_user(
                username=username,
                email=email,
                first_name=first_name,
                last_name=last_name
            )
            if user:
                user.set_password(password)
                user.save()
                return redirect('/login')
            else:
                messages.error(request, message="Error occurred and your account was not created successfully, "
                                                "let's give it another shot")
                return redirect(request.path_info)

    return render(request, 'profiles/Register.html')


def Login(request):
    if request.user.is_authenticated:
        return redirect('apps:index')

    if request.method == "POST":
        email = request.POST.get('email')
        password = request.POST.get('password')

        if email == "" or password == "":
            messages.error(request, "Email/Username and password are required")
            return redirect(request.path_info)

        login_attempt = auth.authenticate(
            email=email, password=password)
        if login_attempt is not None:
            auth.login(request, login_attempt)
            messages.success(request, "You are logged in")
            if request.GET.get('next'):
                return redirect(request.GET.get('next'))
            return redirect('apps:index')
        else:
            messages.error(request, "No user is associated with the given credentials.")
    return render(request, 'profiles/Login.html')

templates/apps/index.html
{% extends "base.html" %}

{% block title %}
    Index Page
{% endblock %}

{% block content %}
hello world
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title  %} JETAUTH {% endblock title %}</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{% static "css/materialize.min.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
</head>
<body>

{# navbar #}
<nav class="light-blue lighten-1" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="{% url 'apps:index' %}" class="brand-logo">JETAUTHER</a>
        <ul class="right hide-on-med-and-down">
            <li><a href="#">Developer</a></li>
            <li><a href="#">Profile</a></li>
            <li><a href="#">My apps</a></li>
            <li><a href="#">Logout</a></li>
        </ul>

        <ul id="nav-mobile" class="sidenav">
            <h3 class="blue-text"> <span class="material-icons">menu</span> <span>Menu</span></h4>
            <li><a href="#">Developer</a></li>
             <li><a href="#">Profile</a></li>
            <li><a href="#">My apps</a></li>
            <li><a href="#">Logout</a></li>
        </ul>
        <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    </div>
</nav>


{% block content %}

{% endblock content  %}


{# footer #}

<footer class="page-footer light-blue lighten-1">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <h5 class="white-text">JETAUTHER</h5>
                <p class="grey-text text-lighten-4">
                A one stop center for all the authentication, design your app, let's us take care of the authentication.
                </p>

            </div>
            <div class="col l3 s12">
                <h5 class="white-text">Getting started</h5>
                <ul>
                    <li><a class="white-text" href="#!">Developer docs</a></li>
                    <li><a class="white-text" href="#!">Create account</a></li>
                    <li><a class="white-text" href="#!">Login</a></li>
                </ul>
            </div>
            <div class="col l3 s12">
                <h5 class="white-text">Community</h5>
                <ul>
                    <li><a class="white-text" href="#!">Apps</a></li>
                    <li><a class="white-text" href="#!">Users</a></li>
                    <li><a class="white-text" href="#!">Talk to us</a></li>
                    <li><a class="white-text" href="#!">Report abuse</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            Made by <a class="orange-text text-lighten-3" href="http://materializecss.com">Materialize</a>
        </div>
    </div>
</footer>


<!--  Scripts-->
<script src="{% static "js/jquery.min.js" %}"></script>
<script src="{% static "js/materialize.min.js" %}"></script>
<script src="{% static "js/init.js" %}"></script>
</body>
</html>

{% block script %}

{% endblock %}

templates/index.html
  <div class="section no-pad-bot" id="index-banner">
    <div class="container">
      <br><br>
      <h1 class="header center orange-text">Starter Template</h1>
      <div class="row center">
        <h5 class="header col s12 light">A modern responsive front-end framework based on Material Design</h5>
      </div>
      <div class="row center">
        <a href="http://materializecss.com/getting-started.html" id="download-button" class="btn-large waves-effect waves-light orange">Get Started</a>
      </div>
      <br><br>

    </div>
  </div>


  <div class="container">
    <div class="section">

      <!--   Icon Section   -->
      <div class="row">
        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center light-blue-text"><i class="material-icons">flash_on</i></h2>
            <h5 class="center">Speeds up development</h5>

            <p class="light">We did most of the heavy lifting for you to provide a default stylings that incorporate our custom components. Additionally, we refined animations and transitions to provide a smoother experience for developers.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center light-blue-text"><i class="material-icons">group</i></h2>
            <h5 class="center">User Experience Focused</h5>

            <p class="light">By utilizing elements and principles of Material Design, we were able to create a framework that incorporates components and animations that provide more feedback to users. Additionally, a single underlying responsive system across all platforms allow for a more unified user experience.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center light-blue-text"><i class="material-icons">settings</i></h2>
            <h5 class="center">Easy to work with</h5>

            <p class="light">We have provided detailed documentation as well as specific code examples to help new users get started. We are also always open to feedback and can answer any questions a user may have about Materialize.</p>
          </div>
        </div>
      </div>

    </div>
    <br><br>
  </div>

templates/profiles/Login.html
{% extends "base.html" %} {% block title %} Login {% endblock %}
<form class="accent-1"></form>

{% block content %}
<div class="row section">
    <h3>Login to your account</h3>
<form method="post" class=" col s12" >
    {% csrf_token %}
    <div class="input-field">
        <label for="email">Email address</label>
        <input type="email" name="email" id="email">
    </div>

    <div class="input-field">
        <label for="password">Enter your password</label>
        <input type="password" name="password" id="password">
    </div>

    <div class="section">
        <button type="submit" class="btn">Login</button>
        </div>
        <div class="divider"></div>
        <div class="section">
        <a href="{% url 'profiles:register' %}" class="flex">Create your one time account</a>
    </div>
</form>
</div>
{% endblock %}</p>

templates/profiles/Register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>